apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-challenge-persistent-volume
  labels:
    type: local
spec:
  storageClassName: tech-challenge-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data/postgres"
