services:
  app:
    build: .
    container_name: tech-challenge-app
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8357:8357'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    networks:
      - tcnetwork
  db:
    image: 'postgres:latest'
    container_name: tech-challenge-db
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - tcnetwork

volumes:
  db:
    driver: local

networks:
  tcnetwork:
    name: tech-challenge-network