apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app-service
  namespace: techchallenge
spec:
  selector:
    app: tech-challenge-app
  ports:
    - port: 8357
      targetPort: 8357
  clusterIP: None