apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-db-service
  namespace: techchallenge
  labels:
    app: tech-challenge-db-service
spec:
  selector:
    app: tech-challenge-db-statefulset
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
