apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-db-service
  namespace: techchallenge
spec:
  selector:
    app: tech-challenge-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
