adminPassword: "password"

service:
  type: NodePort
  nodePort: 30002

persistence:
  enabled: true
  size: 10Gi

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: "/var/lib/grafana/dashboards"

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'Dashboards'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true

grafana.ini:
  "dashboards":
    min_refresh_interval: "1s"   # Set minimum refresh interval to 1 second