CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE CUSTOMER (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL,
    DOCUMENT VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);