CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE PRODUCT (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    NAME VARCHAR(60) NOT NULL,
    CATEGORY VARCHAR(15) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    DESCRIPTION VARCHAR(60) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);