CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "customer_order" (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CUSTOMER_ID UUID REFERENCES CUSTOMER(id),
    AMOUNT DECIMAL(10, 2) NOT NULL,
    SEQUENCE INT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    IS_PAID BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);
