CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE CUSTOMER_ORDER (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CUSTOMER_ID UUID REFERENCES CUSTOMER(id),
    AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_ID VARCHAR(255),
    SEQUENCE INT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    IS_PAID BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);
