apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-persistent-volume-claim
  namespace: techchallenge
spec:
  storageClassName: tech-challenge-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
